name: Lint and Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths:
      - 'pgo/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Lint chart
        run: helm lint pgo

      - name: Template chart
        run: helm template test pgo
